defaults: &defaults
  host: localhost
#  slaves:
#    - host: slave1.local
#      port: 27018
#    - host: slave2.local
#      port: 27019
  allow_dynamic_fields: false
  parameterize_keys: false
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: false

development:
  <<: *defaults
  database: etpr3_development

test:
  <<: *defaults
  database: etpr3_test

# set these environment variables on your prod server
production:
  <<: *defaults
#  host: <%= ENV['MONGOID_HOST'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  username: user
#  password: pass
#  database: <%= ENV['MONGOID_DATABASE'] %>
  database: etpr3_production
