defaults: &defaults
  app_key: 12004444
  secret_key: b1097ad2f942ff8df43cff28ab826052
  taobaoke_pid: mm_14283632_0_0
  taobaoke_nick: 淘江山更淘美人

development:
  <<: *defaults
  is_sandbox: false
  use_curl: false

test:
  <<: *defaults
  is_sandbox: ture
  use_curl: false

production:
  <<: *defaults
  is_sandbox: false
  use_curl: true
